services:
  postgres:
    image: postgres:16-alpine
    container_name: parking-api-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parking_dev
    ports:
      - "5432:5432"
